export type KamishibaiCut = {
  id: string;
  duration: number;
  characters: string;
  location: string;
  image: string;
  caption: string;
};

export const kamishibaiCuts: KamishibaiCut[] = [
  {
    id: "pv_001",
    duration: 1.5,
    characters: "",
    location: "rainy roadside",
    image: "pv_001.jpg",
    caption: "雨の国道沿い、深夜のコンビニ外観",
  },
  {
    id: "pv_002",
    duration: 1.5,
    characters: "",
    location: "store aisle",
    image: "pv_002.jpg",
    caption: "店内の蛍光灯、誰もいない通路",
  },
  {
    id: "pv_003",
    duration: 1.2,
    characters: "",
    location: "wall clock",
    image: "pv_003.jpg",
    caption: "午前2時3分を指す壁時計",
  },
  {
    id: "pv_004",
    duration: 1.3,
    characters: "Register 13",
    location: "cash counter",
    image: "pv_004.jpg",
    caption: "レジカウンター奥で青い光が点く",
  },
  {
    id: "pv_005",
    duration: 1.5,
    characters: "Register 13",
    location: "cash counter",
    image: "pv_005.jpg",
    caption: "第十三レジの画面が薄く起動する",
  },
  {
    id: "pv_006",
    duration: 1.5,
    characters: "Takumi",
    location: "back room door",
    image: "pv_006.jpg",
    caption: "タクミがバックヤードから出てくる",
  },
  {
    id: "pv_007",
    duration: 1.5,
    characters: "Takumi",
    location: "store counter",
    image: "pv_007.jpg",
    caption: "タクミの困惑顔アップ",
  },
  {
    id: "pv_008",
    duration: 1.5,
    characters: "Mina",
    location: "cash counter",
    image: "pv_008.jpg",
    caption: "ミナが無表情でレジ横に立つ",
  },
  {
    id: "pv_009",
    duration: 1.5,
    characters: "Register 13",
    location: "cash counter",
    image: "pv_009.jpg",
    caption: "レジ画面に返品受付のような光",
  },
  {
    id: "pv_010",
    duration: 1.5,
    characters: "Future Salaryman",
    location: "store entrance",
    image: "pv_010.jpg",
    caption: "自動ドアの外に濡れた人影",
  },
  {
    id: "pv_011",
    duration: 1.5,
    characters: "Future Salaryman",
    location: "store entrance",
    image: "pv_011.jpg",
    caption: "未来の会社員が入店する",
  },
  {
    id: "pv_012",
    duration: 1.5,
    characters: "Future Salaryman",
    location: "store aisle",
    image: "pv_012.jpg",
    caption: "雨粒と乱れたネクタイ",
  },
  {
    id: "pv_013",
    duration: 1.5,
    characters: "Future Salaryman",
    location: "product closeup",
    image: "pv_013.jpg",
    caption: "未来の商品パッケージ",
  },
  {
    id: "pv_014",
    duration: 1.5,
    characters: "Takumi",
    location: "store counter",
    image: "pv_014.jpg",
    caption: "タクミが商品を見て固まる",
  },
  {
    id: "pv_015",
    duration: 1.5,
    characters: "Mina",
    location: "barcode scan",
    image: "pv_015.jpg",
    caption: "ミナがバーコードを読む",
  },
  {
    id: "pv_016",
    duration: 1.5,
    characters: "Register 13",
    location: "barcode scan",
    image: "pv_016.jpg",
    caption: "バーコードリーダーの赤い線",
  },
  {
    id: "pv_017",
    duration: 1.5,
    characters: "Register 13",
    location: "cash counter",
    image: "pv_017.jpg",
    caption: "通常表示から異常表示へ",
  },
  {
    id: "pv_018",
    duration: 1.5,
    characters: "",
    location: "drink shelves",
    image: "pv_018.jpg",
    caption: "冷蔵棚に未来都市の影",
  },
  {
    id: "pv_019",
    duration: 1.5,
    characters: "Future Salaryman",
    location: "counter closeup",
    image: "pv_019.jpg",
    caption: "未来の会社員の手が震える",
  },
  {
    id: "pv_020",
    duration: 1.5,
    characters: "",
    location: "product closeup",
    image: "pv_020.jpg",
    caption: "おにぎりが青白く照らされる",
  },
  {
    id: "pv_021",
    duration: 1.5,
    characters: "Takumi",
    location: "cash counter",
    image: "pv_021.jpg",
    caption: "タクミがツッコミ気味に身を乗り出す",
  },
  {
    id: "pv_022",
    duration: 1.5,
    characters: "Mina",
    location: "cash counter",
    image: "pv_022.jpg",
    caption: "ミナが静かに制止する",
  },
  {
    id: "pv_023",
    duration: 1.5,
    characters: "Register 13",
    location: "receipt printer",
    image: "pv_023.jpg",
    caption: "レシートが勝手に吐き出される",
  },
  {
    id: "pv_024",
    duration: 1.5,
    characters: "",
    location: "receipt closeup",
    image: "pv_024.jpg",
    caption: "レシートに未来の日付",
  },
  {
    id: "pv_025",
    duration: 1.5,
    characters: "",
    location: "store lights",
    image: "pv_025.jpg",
    caption: "店内照明が一瞬落ちる",
  },
  {
    id: "pv_026",
    duration: 1.5,
    characters: "Register 13",
    location: "cash counter",
    image: "pv_026.jpg",
    caption: "第十三レジの顔のような表示",
  },
  {
    id: "pv_027",
    duration: 1.5,
    characters: "Future Salaryman",
    location: "store aisle",
    image: "pv_027.jpg",
    caption: "未来の街の残像",
  },
  {
    id: "pv_028",
    duration: 2,
    characters: "Takumi Mina Future Salaryman Register 13",
    location: "cash counter",
    image: "pv_028.jpg",
    caption: "四者構図",
  },
  {
    id: "pv_029",
    duration: 1.5,
    characters: "Mina",
    location: "counter closeup",
    image: "pv_029.jpg",
    caption: "ミナの無表情な横顔",
  },
  {
    id: "pv_030",
    duration: 1.5,
    characters: "Takumi",
    location: "counter closeup",
    image: "pv_030.jpg",
    caption: "タクミの決意顔",
  },
  {
    id: "pv_031",
    duration: 1.5,
    characters: "",
    location: "product closeup",
    image: "pv_031.jpg",
    caption: "商品が光る",
  },
  {
    id: "pv_032",
    duration: 1.5,
    characters: "",
    location: "store exterior",
    image: "pv_032.jpg",
    caption: "雨が逆向きに流れる",
  },
  {
    id: "pv_033",
    duration: 1.5,
    characters: "",
    location: "automatic door",
    image: "pv_033.jpg",
    caption: "自動ドア越しの青い店内",
  },
  {
    id: "pv_034",
    duration: 2,
    characters: "Register 13",
    location: "cash counter",
    image: "pv_034.jpg",
    caption: "第十三レジのアップ",
  },
  {
    id: "pv_035",
    duration: 2,
    characters: "",
    location: "store exterior",
    image: "pv_035.jpg",
    caption: "窓に人物の影",
  },
  {
    id: "pv_036",
    duration: 2,
    characters: "Register 13",
    location: "title mood",
    image: "pv_036.jpg",
    caption: "第十三レジ",
  },
];

export const kamishibaiDurationInFrames = kamishibaiCuts.reduce(
  (total, cut) => total + Math.round(cut.duration * 30),
  0,
);
