import type { KamishibaiCut } from "./kamishibaiCuts";

export const kamishibaiCutsAseda: KamishibaiCut[] = [
  {
    id: "aseda_001",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "research parking lot",
    image: "aseda_001.jpg",
    caption: "夜の研究所駐車場、汗田がバイクに跨る",
  },
  {
    id: "aseda_002",
    duration: 1.3,
    characters: "Aseda Ryuji",
    location: "helmet closeup",
    image: "aseda_002.jpg",
    caption: "紫のヘルメットとサングラスのアップ",
  },
  {
    id: "aseda_003",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "bike cockpit",
    image: "aseda_003.jpg",
    caption: "バイクのナビにSOS、第十三レジを探してほしい",
  },
  {
    id: "aseda_004",
    duration: 1.3,
    characters: "Aseda Ryuji",
    location: "helmet closeup",
    image: "aseda_004.jpg",
    caption: "汗田が眉をひそめる",
  },
  {
    id: "aseda_005",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "road at night",
    image: "aseda_005.jpg",
    caption: "雨上がりの国道を走るバイク",
  },
  {
    id: "aseda_006",
    duration: 1.5,
    characters: "",
    location: "road at night",
    image: "aseda_006.jpg",
    caption: "コンビニの灯りが見える",
  },
  {
    id: "aseda_007",
    duration: 1.5,
    characters: "Takumi",
    location: "store counter",
    image: "aseda_007.jpg",
    caption: "店内でタクミが驚く",
  },
  {
    id: "aseda_008",
    duration: 1.5,
    characters: "Mina",
    location: "cash counter",
    image: "aseda_008.jpg",
    caption: "ミナが汗田を静かに観察する",
  },
  {
    id: "aseda_009",
    duration: 1.5,
    characters: "Aseda Ryuji Register 13",
    location: "cash counter",
    image: "aseda_009.jpg",
    caption: "汗田が第十三レジを見る",
  },
  {
    id: "aseda_010",
    duration: 1.5,
    characters: "Aseda Ryuji Register 13",
    location: "cash counter",
    image: "aseda_010.jpg",
    caption: "レジ画面の挙動を技術者目線で読む",
  },
  {
    id: "aseda_011",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "counter closeup",
    image: "aseda_011.jpg",
    caption: "汗田の手元、古い技術メモ",
  },
  {
    id: "aseda_012",
    duration: 2,
    characters: "Aseda Ryuji Register 13",
    location: "cash counter",
    image: "aseda_012.jpg",
    caption: "バイクのナビとレジが同時に光る",
  },
  {
    id: "aseda_013",
    duration: 1.5,
    characters: "",
    location: "store aisle",
    image: "aseda_013.jpg",
    caption: "未来の道路標識の幻影",
  },
  {
    id: "aseda_014",
    duration: 1.3,
    characters: "Aseda Ryuji",
    location: "counter closeup",
    image: "aseda_014.jpg",
    caption: "汗田の真剣な顔",
  },
  {
    id: "aseda_015",
    duration: 1.5,
    characters: "Takumi",
    location: "store counter",
    image: "aseda_015.jpg",
    caption: "タクミが何なんですかこの人と言いたげな顔",
  },
  {
    id: "aseda_016",
    duration: 1.5,
    characters: "Mina",
    location: "cash counter",
    image: "aseda_016.jpg",
    caption: "ミナが冷静にレジ操作",
  },
  {
    id: "aseda_017",
    duration: 1.5,
    characters: "Register 13",
    location: "receipt closeup",
    image: "aseda_017.jpg",
    caption: "レシートに未知の座標",
  },
  {
    id: "aseda_018",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "store entrance",
    image: "aseda_018.jpg",
    caption: "汗田のバイクのヘッドライト",
  },
  {
    id: "aseda_019",
    duration: 2,
    characters: "Register 13",
    location: "cash counter",
    image: "aseda_019.jpg",
    caption: "レジから青い光が床に伸びる",
  },
  {
    id: "aseda_020",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "counter closeup",
    image: "aseda_020.jpg",
    caption: "汗田がヘルメットを握り直す",
  },
  {
    id: "aseda_021",
    duration: 1.5,
    characters: "",
    location: "store exterior",
    image: "aseda_021.jpg",
    caption: "店外、未来へ続くような夜道",
  },
  {
    id: "aseda_022",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "counter closeup",
    image: "aseda_022.jpg",
    caption: "汗田の横顔、少しだけ笑う",
  },
  {
    id: "aseda_023",
    duration: 1.5,
    characters: "Aseda Ryuji",
    location: "store exterior",
    image: "aseda_023.jpg",
    caption: "バイクとコンビニのシルエット",
  },
  {
    id: "aseda_024",
    duration: 2.5,
    characters: "Aseda Ryuji",
    location: "title mood",
    image: "aseda_024.jpg",
    caption: "ナビが未来を案内しました",
  },
];

export const kamishibaiAsedaDurationInFrames = kamishibaiCutsAseda.reduce(
  (total, cut) => total + Math.round(cut.duration * 30),
  0,
);
